server:
    port: 8080

spring:
    datasource:
        url: jdbc:postgresql://dpg-cpii07mct0pc73frrf10-a/myspring_0pg6
        username: admin
        password: e0W37gpl1CbM3fmxbtXvYlCmVIugUdmy
        driver-class-name: org.postgresql.Driver
        initialize: true

    jpa: 
        hibernate:
            ddl-auto: create-drop
            generate-ddl: true

    sql:
        init:
            schema-locations: classpath:/schema-postgresql.sql
            mode: always
            platform: postgres